#!/bin/bash

source config

release=$(sed -n -e "s/',//" -e "s/^[ \t]*'version' => '//p" src/config.php)
branchName="release/$release"

git remote add upstream $UPSTREAM

git checkout master
git pull
git checkout -b feature/base-merge
git fetch upstream $branchName && \
git merge upstream/$branchName --no-edit
