#!/bin/bash

source config

branchName=$1

if [ ! $1 ]
then
  release=$(sed -n -e "s/',//" -e "s/^[ \t]*'version' => '//p" src/config.php)
  branchName="release/$release"
fi

if [[ -z $baseRemote ]]
then
	git remote add upstream $UPSTREAM
fi

git checkout master
git pull
git checkout -b feature/base-merge
git fetch upstream $branchName && \
git merge upstream/$branchName --no-edit
