#!/bin/bash

sed -e "/lock '3.4.0'/s/^/# /g" deploy/config/deploy.rb > deploy/config/deploy.rb.new
mv deploy/config/deploy.rb.new deploy/config/deploy.rb
wait

docker run --rm -it -v"$(pwd):/opt" -v ~/.ssh/opia_rackspace_rsa:/root/.ssh/id_rsa -v ~/.ssh/opia_rackspace_rsa.pub:/root/.ssh/id_rsa.pub capistrano cap $@

sed -e "s/# lock '3.4.0'/lock '3.4.0'/g" deploy/config/deploy.rb > deploy/config/deploy.rb.new
mv deploy/config/deploy.rb.new deploy/config/deploy.rb

rm -rf log
