#!/bin/bash

main() {
  if [ -f 'src/.env.example' ]; then
    echo '> Pulling changes from the remote repository..'
    git pull

    if [ ! -f 'src/.env' ]; then
      generateEnvFile
      rm -rf node_modules
      echo '> Installing dependencies in the background..'
      installDependencies > /dev/null 2>&1 &
      bin/docker-dev build --pull
    fi

    if [ -f 'docker-compose.dev.yml' ]; then
      git stash

      if [ -f 'docker-compose.build.yml' ]; then
        echo '> Ignoring maildev links..'
        sed -e '1s/    links:/#   links:/;t' -e '1,/    links:/s//#   links:/' -e '1s/      - maildev/#     - maildev/;t' -e '1,/      - maildev/s//#     - maildev/' docker-compose.dev.yml > docker-compose.dev.yml.new
        mv docker-compose.dev.yml.new docker-compose.dev.yml
      fi

      echo '> Launching Docker images in daemon mode..'
      bin/docker-dev-up -d nginx-proxy

      migrateDatabase

      git checkout -- .
      git stash pop

      local ipAddress=$(bin/docker-dev port nginx-proxy 443)

      sed -e 's/APP_HOST=.*/APP_HOST='${ipAddress}'/g' src/.env > src/.env.new
      echo '> Set APP_HOST to' ${ipAddress}
      mv src/.env.new src/.env

      /usr/bin/open -a '/Applications/Google Chrome.app' https://${ipAddress}
      echo '> Site running in Chrome at URL: https://'${ipAddress}
      echo '> Setup complete'
    else
      echo 'ERROR: No docker-compose.dev.yml file found.'
      echo 'Please use Vagrant instead.'
    fi
  else
    echo 'ERROR: No .env.example file found.'
  fi

  exit 0
}

generateEnvFile() {
  echo '> Generating .env file..'
  sed -e 's/APP_IN_TEST_MODE=false/APP_IN_TEST_MODE=true/g' -e 's/CACHE_DRIVER=filesystem/CACHE_DRIVER=array/g' -e '/SMTP_SERVER=maildev/s/^/# /g' src/.env.example > src/.env
  echo '> Set APP_IN_TEST_MODE to true'
  echo '> Set CACHE_DRIVER to array'
  echo '> Commented out SMTP_SERVER=maildev'
}

installDependencies() {
  composer install
  yarn --frozen-lockfile
}

migrateDatabase() {
  echo '> Migrating database..'

  if [ -f 'docker/wait-for-it.sh' ]; then
    bin/docker-dev run builder docker/wait-for-it.sh mysql:3306 -t 90
    bin/docker-dev-migrate
  else
    bin/docker-dev run -w /opt web "php src/vendor/bin/phinx migrate"
  fi
}

main "$@"
