#!/bin/bash

set -e

main() {
	git checkout release/$1.0.0
	git pull

	local firstBranch=release/$1.0.0;
	local targetBranch=release/$2.0.0;

	if [ $2 == 'm' ]; then
	  targetBranch='master'
	fi

	git checkout $targetBranch
	git pull
	git checkout -b feature/$1-into-$2
	echo "Merging $firstBranch into feature/$1-into-$2"
	git merge $firstBranch --no-edit
}

main "$@"
